# -*- coding: utf-8 -*-
"""brain-tomur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vSxl_lK8-oKawSu5IMNpwUc2g298mcS
"""

pip install numpy opencv-python matplotlib tensorflow scikit-learn

from google.colab import drive
drive.mount('/content/drive')

from imutils import paths
import matplotlib.pyplot as plt
import argparse
import os
import cv2

# File Handling, Numerical Operations, Image Processing, Visualisation, Deep Learning, and Delete Folder
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import time

# Building and Evaluating the CNN Model
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.metrics import AUC, Precision, Recall
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

# Data Splitting, Class Balancing, and Performance Evaluation
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, f1_score, confusion_matrix, roc_curve, roc_auc_score, accuracy_score

def load_mri(folder, label, target_size):
    images = []
    labels = []

    for dirname, _, filenames in os.walk(folder):
        for filename in filenames:
            path = os.path.join(dirname, filename)
            mri_img = cv2.imread(path)  # Read image
            if mri_img is not None:
                mri_img = cv2.resize(mri_img, target_size)  # Resize image
                images.append(mri_img)
                labels.append(label)

    return images, labels

target_size = (128, 128)

positive, positive_labels = load_mri('/content/drive/MyDrive/Brain_Tumor_Dataset/Positive', 1, target_size)
negative, negative_labels = load_mri('/content/drive/MyDrive/Brain_Tumor_Dataset/Negative', 0, target_size)

X = np.array(positive + negative) / 255.0   # Divide by 255 to Normalise Pixel Values 0 to 1
y = np.array(positive_labels + negative_labels) # Combine Labels

train_mri, test_mri, train_labels, test_labels = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(train_labels), y=train_labels)
class_weight_dict = dict(enumerate(class_weights))
print("Class Weights:", class_weight_dict) # Print Class Weights

aug = ImageDataGenerator(rotation_range=15, zoom_range=0.1, horizontal_flip=True)

brain_tumour_cnn = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)), # 1. Conv Layer
    MaxPooling2D(2, 2), # 1. Pooling Layer
    Conv2D(64, (3, 3), activation='relu'), # 2. Conv Layer
    MaxPooling2D(2, 2), # 2. Pooling Layer
    Flatten(), # Output to 1D
    Dropout(0.5), # Prevent Overfitting
    Dense(128, activation='relu'), # Fully Connected Layer
    Dense(1, activation='sigmoid') # Output Layer for Binary Classification
])

brain_tumour_cnn.compile(
    optimizer='adam', # Optimiser
    loss='binary_crossentropy', # Loss Function
    metrics=['accuracy', AUC(), Precision(), Recall()] # Evaluate
)
brain_tumour_cnn.summary()

model_save_path = '/content/drive/MyDrive/Brain_Tumor_Dataset/model'
if not os.path.exists(model_save_path):
    os.makedirs(model_save_path)

save_best = ModelCheckpoint(
    os.path.join(model_save_path, 'brain_cnn.keras'),
    monitor='val_accuracy',
    save_best_only=True,
    mode='max',
    verbose=1
)

stop_training = EarlyStopping(
    monitor='val_accuracy',
    patience=5, # Wait 5 Epochs Before Early Stopping
    restore_best_weights=True, # Restore Weights from Best Epoch
    verbose=1
)

start_time = time.time()
hist = brain_tumour_cnn.fit(
    aug.flow(train_mri, train_labels, batch_size=32), # Use Augmented Images
    epochs=50,
    validation_data=(test_mri, test_labels),
    callbacks=[save_best, stop_training],
    class_weight=class_weight_dict # Apply Balanced Class Weights
)

end_time = time.time()
elapsed_time = end_time - start_time
train_mins = int(elapsed_time // 60)
train_secs = int(elapsed_time % 60)

def training_stats(hist, test_labels, y_pred, y_pred_prob):
    stats = ['accuracy', 'loss', 'precision', 'recall', 'auc'] # Metrics
    for stat in stats:
        if stat in hist.history:
            plt.figure()
            plt.plot(hist.history[stat], label=f"Train {stat.capitalize()}")
            plt.plot(hist.history[f"val_{stat}"], label=f"Validation {stat.capitalize()}")
            plt.title(f"Training and Validation {stat.capitalize()}")
            plt.xlabel("Epoch")
            plt.ylabel(stat.capitalize())
            plt.legend()
            plt.grid(True)
            plt.tight_layout()
            plt.show() # Display All Plots

    # Confusion Matrix
    cm = confusion_matrix(test_labels, y_pred) # Create Confusion Matrix
    plt.imshow(cm, cmap='Blues') # Visualise Confusion Matrix
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.xticks([0,1], ['No Tumour', 'Tumour'])
    plt.yticks([0,1], ['No Tumour', 'Tumour'])
    plt.colorbar()
    plt.tight_layout()
    plt.show() # Display Confusion Matrix

    # ROC Curve
    fpr, tpr, _ = roc_curve(test_labels, y_pred_prob) # Calculate FP and TP Rates
    auc_val = roc_auc_score(test_labels, y_pred_prob) # Calculates AUC
    plt.plot(fpr, tpr, label=f"Model (AUC = {auc_val:.2f})")
    plt.title("ROC Curve")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend(loc='lower right')
    plt.grid(True)
    plt.tight_layout()
    plt.show() # Display ROC Curve

tumour_model = load_model(os.path.join(model_save_path, 'brain_cnn.keras'))

# Make Predictions on 20% Test Data
y_pred_prob = tumour_model.predict(test_mri)  # Probability Score
y_pred = (y_pred_prob > 0.5).astype(int).flatten()  # Binary Class Pred

# Compute Evaluation Statistics
report = classification_report(test_labels, y_pred)
f1_score_val = f1_score(test_labels, y_pred)
auc_val = roc_auc_score(test_labels, y_pred_prob)
accuracy = accuracy_score(test_labels, y_pred)
conf_matrix = confusion_matrix(test_labels, y_pred)
val_acc = max(hist.history['val_accuracy'])
error_analysis = [i for i in range(len(test_labels)) if test_labels[i] != y_pred[i]]
misclassified_val = len(error_analysis) # Number of Misclassified Images
total_samples = len(test_labels)

print("Report:\n", report)
print("Stats:")
print(f"Final Accuracy         : {accuracy:.4f}")
print(f"F1 Score               : {f1_score_val:.4f}")
print(f"AUC Score              : {auc_val:.4f}")
print(f"Validation Accuracy    : {val_acc:.4f}")
print(f"Training Time          : {train_mins} minutes {train_secs} seconds")
print(f"Misclassified Images   : {misclassified_val} out of {total_samples}\n")
print(f"Confusion Matrix:\n{conf_matrix}")

training_stats(hist, test_labels, y_pred, y_pred_prob)